"""Initial migration

Revision ID: a97f24cf0b23
Revises: 
Create Date: 2025-05-04 02:32:17.729527

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a97f24cf0b23'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alquileres', schema=None) as batch_op:
        batch_op.alter_column('fecha_creacion',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_constraint('alquileres_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['id_usuario'], ['id_usuario'], ondelete='CASCADE')

    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.drop_constraint('pagos_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'alquileres', ['id_alquiler'], ['id_alquiler'], ondelete='CASCADE')

    with op.batch_alter_table('propiedades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('banos', sa.Integer(), nullable=True))
        batch_op.alter_column('precio',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
        batch_op.drop_column('baños')

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('rol', sa.String(length=20), nullable=True))
        batch_op.alter_column('fecha_registro',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('fecha_registro',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_column('rol')
        batch_op.drop_column('activo')

    with op.batch_alter_table('propiedades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('baños', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.alter_column('precio',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
        batch_op.drop_column('banos')

    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('pagos_ibfk_1', 'alquileres', ['id_alquiler'], ['id_alquiler'])

    with op.batch_alter_table('alquileres', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('alquileres_ibfk_1', 'usuarios', ['id_usuario'], ['id_usuario'])
        batch_op.alter_column('fecha_creacion',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    # ### end Alembic commands ###
